# Configuración base del repositorio (Parámetros del dataform.json)
defaultProject: fsp-pipeline-project
defaultDataset: fsp_silver, fsp_gold
defaultAssertionDataset: fsp_silver_assertions
defaultLocation: US